### PR TITLE
Added Sharing::size() method to retrieve size

### PR DESCRIPTION
**Pull request by jean-airoldie**
This method can be used to retrieve the size of the memory-mapped region, which is especially useful when using a `Shared<c_void>`.

My specific use case is to retrieve the size of an allocated `Shared<c_void>` without having to trust the peer. For instance one could put allocated size in the shared memory itself, but that could be maliciously modified by the peer.

There is some additional formatting diff due to running nightly rustfmt, I can undo that if you prefer.

### CODE REVIEW

**Comment by Ekleog** [comment]
Looks good to me, thank you!

**Comment by Ekleog** [comment]
Oh, and I just wanted to mention: shared memory without trusting the peer is a really hard problem on posix, especially due to `truncate` being a thing. Just saying that in case it can help, it doesn't reduce the usefulness of this addition, as there's no reason to put the size in the shared memory given it should already be available as metadata :)

**Comment by jean-airoldie** [comment]
@Ekleog I plan on using memfd seals (F_SEAL_GROW | F_SEAL_SHRINK | F_SEAL_SEAL) to prevent an untrusted peer to cause SIGBUS by truncating the file like you mentioned. I'm also manipulating the shared memory as a `&[AtomicU8]` instead of `&[u8]` to prevent collisions (although its not necessary for x86 AFAIK). Hopefully that should be enough.

**Comment by Ekleog** [comment]
FWIW, manipulating the shared memory as `&[AtomicU8]` is probably going to be awfully slow. You may want to have a look at using raw pointers and the `*volatile*` series of functions, which are designed for this (memory-mapped IO) use case :)

Also, you do need to not mutate `&[u8]` under the hood (which would be the case if taking an `&[u8]` to a region shared with an untrusted process), because otherwise it'd be Rust UB (and LLVM UB), and the compiler might do optimizations that assume this and will make monkeys fly out of your nose if it ever happens to not hold — which would be a dream for an attacker who'll make sure to mutate the worst thing at the worst time ;)

**Comment by jean-airoldie** [comment]
> FWIW, manipulating the shared memory as &[AtomicU8] is probably going to be awfully slow.

In my specific use case I'm just memcpy'ing the shared bytes and then casting the local copy to `&[u8]` and vice versa.
I benchmarked it and doing so has no performance cost on x86 (at least on the 10yo hardware i tested) for by specific use-case (shared lock-free ringbuffer).

> You may want to have a look at using raw pointers and the *volatile* series of functions, which are designed for this (memory-mapped IO) use case :)

Thanks, looks like what I was looking for.

> Also, you do need to not mutate &[u8] under the hood [...] it'd be Rust UB (and LLVM UB), and the compiler might do optimizations that assume this and will make monkeys fly out of your nose if it ever happens to not hold

Yeah, I'm not manipulating the shared memory directly, only memcpy to and from it.

**Pull request merged**
